### PR TITLE
Create star_pattern.rs

### PR DESCRIPTION
**Pull request by KorryKatti**
added a star pattern with comments to explain easily towards hacktoberfest

#1

### CODE REVIEW

**Comment by SjxSubham** [comment]
**All good, give a star to this repo** 
### Thanks for contribution... _Happy Hacktober..._

**Comment by KorryKatti** [comment]
image
btw

**Comment by SjxSubham** [comment]
raise another PR... it maybe something glitch by github

**Comment by KorryKatti** [comment]
> raise another PR... it maybe something glitch by github

nevermind

**Pull request merged**
